#dsn="root:@tcp(localhost)/udpp2"
blockdbDatabase="tech_anlink_alicloud"
configDatabase="tech_anlink_alicloud"
port=2001
logfile="logfile"
enableCors=true
auth=false
loglevel="debug"
mongourl="mongodb://localhost:27017"
blockDB="mongodb://localhost:27017"
# blockDB="mongodb://udpp:udpp123@47.100.222.11:30007"

blockAddress="http://47.100.222.11:10003/blockQuery/"

https=false
cert="aliyun.pem"
key="aliyun.key"
